"""Framework-wide semantic naming and metric metadata helpers."""

from __future__ import annotations

from typing import Any


AGGREGATION_PREFIXES = {
    "average": "avg",
    "sum": "total",
    "count": "count",
    "median": "median",
    "min": "min",
    "max": "max",
    "std": "std",
    "p05": "p05",
    "p25": "p25",
    "p75": "p75",
    "p95": "p95",
}

PREFIX_TO_AGGREGATION = {value: key for key, value in AGGREGATION_PREFIXES.items()}


def build_semantic_metric_name(source_column: str, aggregation: str) -> str:
    """Create a descriptive metric column name from a source column and aggregation."""
    if source_column == "record_count":
        return "record_count"

    prefix = AGGREGATION_PREFIXES.get(aggregation)
    if prefix is None:
        raise ValueError(f"Unsupported semantic aggregation: {aggregation}")

    return f"{prefix}_{source_column}"


def infer_metric_unit(source_column: str | None) -> str | None:
    """Infer a conservative unit from the source metric column name when possible."""
    if source_column is None:
        return "count"

    lowered = source_column.lower()
    if lowered == "record_count" or lowered.startswith("count_"):
        return "count"
    if lowered == "co2" or "co2" in lowered:
        return "million_tonnes_co2"
    if (
        lowered == "gdp"
        or lowered.endswith("_gdp")
        or "gross_domestic_product" in lowered
    ):
        return "current_usd"
    if "renewable_share" in lowered:
        return "percent"
    if "energy_consumption" in lowered or "primary_energy" in lowered:
        return "twh"
    if "inflation" in lowered or lowered.startswith("cpi"):
        return "percent"
    if "unemployment" in lowered:
        return "percent"
    if (
        lowered == "total_artists"
        or lowered.endswith("_artists")
        or "artists_count" in lowered
    ):
        return "count"
    if "revenue" in lowered:
        return "usd"
    if "population" in lowered or "person" in lowered:
        return "persons"
    if "temperature_anomaly" in lowered:
        return "celsius"
    if "sea_level" in lowered:
        return "millimeters"
    if "ice_extent" in lowered or "ice_area" in lowered:
        return "million_square_km"
    if "celsius" in lowered:
        return "celsius"
    if "fahrenheit" in lowered:
        return "fahrenheit"
    if "kelvin" in lowered:
        return "kelvin"

    return None


def parse_semantic_metric_column(column_name: str) -> dict[str, Any] | None:
    """Parse a semantic metric column name back into framework metadata."""
    if column_name == "record_count":
        return {
            "final_column_name": "record_count",
            "source_column": None,
            "aggregation": "count",
            "unit": "count",
            "description": "Count of records in the output table.",
        }

    for prefix, aggregation in PREFIX_TO_AGGREGATION.items():
        marker = f"{prefix}_"
        if column_name.startswith(marker):
            source_column = column_name[len(marker) :]
            return build_metric_metadata(
                final_column_name=column_name,
                source_column=source_column,
                aggregation=aggregation,
            )

    return None


def build_metric_metadata(
    final_column_name: str,
    source_column: str | None,
    aggregation: str,
) -> dict[str, Any]:
    """Build a standard metric metadata payload for semantic outputs."""
    unit = infer_metric_unit(source_column)

    if final_column_name == "record_count":
        description = "Count of records in the generated output."
    elif source_column is None:
        description = f"{aggregation.title()} metric generated by the pipeline."
    else:
        description = f"{aggregation.title()} of `{source_column}` values in the generated output."

    return {
        "final_column_name": final_column_name,
        "source_column": source_column,
        "aggregation": aggregation,
        "unit": unit,
        "description": description,
    }
